name: Build and Deploy App to GCP

on:
  workflow_call:
    inputs:
      INJECT_SECRETS:
        required: false
        type: string

permissions: write-all

jobs:
  deliver:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Create secrets file
        uses: Amadevus/pwsh-script@v2
        with:
          script: ${{ inputs.INJECT_SECRETS }}

      - name: Acceptance test with Gradle
        uses: gradle/gradle-build-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: acceptance

