name: Build project

on:
  workflow_call:
    inputs:
      JDK_VERSION:
        required: false
        type: string
        default: '8'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ inputs.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JDK_VERSION }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew clean build -P"trevorism.test.event=enabled"

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.5.0
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

