name: Build project

on:
  workflow_call:
    inputs:
      JDK_VERSION:
        required: false
        type: string
        default: '8'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ inputs.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JDK_VERSION }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: clean build

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.5.0
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

