name: Build project

on:
  workflow_call:
    inputs:
      JDK_VERSION:
        required: false
        type: string
        default: '21'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up JDK ${{ inputs.JDK_VERSION }}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ inputs.JDK_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew clean build -P"trevorism.test.event=enabled"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v5.6.2
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

