name: Build and Deploy App to GCP

on:
  workflow_call:
    inputs:
      service_account:
        description: 'github-trevorism-<project name>@trevorism-<project name>.iam.gserviceaccount.com'
        required: true
        type: string
      workload_identity_provider:
        description: 'projects/<project id>/locations/global/workloadIdentityPools/github-trevorism-<project name>-pool/providers/trevorism-<project name>-provider'
        required: true
        type: string
      version:
        description: 'Version of app to deploy, in dash form (e.g. 1-3-2)'
        required: true
        type: string
      run_acceptance:
        description: 'Should we run the acceptance tests?'
        required: false
        default: false
        type: boolean
    secrets:
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      SIGNING_KEY:
        required: true

permissions: write-all

jobs:
  deliver:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Auth with google
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          service_account: ${{ inputs.service_account }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: clean build appengineStage

      - name: Create secrets file
        uses: Amadevus/pwsh-script@v2
        id: script
        with:
          script: |
            Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'clientId=${{ secrets.CLIENT_ID }}'
            Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'clientSecret=${{ secrets.CLIENT_SECRET }}'
            Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'signingKey=${{ secrets.SIGNING_KEY }}'

      - name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0.8.0'
        with:
          working_directory: "build/staged-app"
          deliverables: 'app.yaml'
          promote: true
          version: ${{ inputs.version }}

      - name: Acceptance test with Gradle
        if: ${{ inputs.run_acceptance }}
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: acceptance

