name: Gradle Jar Release

on:
  workflow_call:
    inputs:
      NEW_VERSION:
        type: string
        required: true

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build

      - name: Publish to Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          ./gradlew -Pversion=${RELEASE_VERSION} publishRelease

      - name: Replace gradle properties
        run: |
          sed -ie "/version=/ s/=.*/=${{ NEW_VERSION }}/" ./gradle.properties

      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Bump gradle.properties'
          push_options: '--force'