name: Javascript unit tests

on:
  workflow_call:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
      - run: npm install
        working-directory: ./src/app
      - run: npm run accept
        working-directory: ./src/app