name: Gradle Jar Release

on:
  workflow_call:
    inputs:
      JDK_VERSION:
        required: false
        type: string
        default: '21'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK ${{ inputs.JDK_VERSION}}
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ inputs.JDK_VERSION}}
          distribution: 'termurin'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Publish to Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          ./gradlew -Pversion=${RELEASE_VERSION} publishRelease

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.RELEASE_VERSION }}
          version-fragment: 'bug'

      - name: Replace gradle properties
        run: |
          sed -i "/version=/ s/=.*/=${{ steps.bump_version.outputs.next-version }}/" ./gradle.properties

      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Bump gradle.properties'
          branch: 'master'
          push_options: '--force'