name: Testing a community wf action

on:
  push:
    branches: [ '**' ]
  pull_request:


permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true # to only include folders in the output
          format: json # either json, csv or newline
      - name: Echo
        run: echo ${{ steps.get_changed.outputs.changed }}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            database:
              - 'database/**'

      # run only if 'backend' files were changed
      - name: backend tests
        if: steps.filter.outputs.database == 'true'
        run: echo ${{ steps.filter.outputs.database }}