name: Testing a community wf action

on:
  push:
    branches: [ '**' ]
  pull_request:


permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          foldersOnly: true # to only include folders in the output
          format: json # either json, csv or newline
      - name: Echo
        run: echo ${{ steps.get_changed.outputs.changed }}